name: tempo_dingo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  feather_icons_flutter: ^4.7.4

  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.4
  rxdart: ^0.18.0
  http: ^0.12.0+1
  spotify: ^0.2.0
  email_validator: ^1.0.4
  flutter_email_sender: ^2.2.2
  random_string: ^2.0.1
  carousel_slider: ^1.4.1
  device_info: ^0.4.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/france.png
    - assets/images/united-states.png
    - assets/images/spain.png
  fonts:
    - family: Apple
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
    - family: Apple-Semibold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
    - family: Apple-Bold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
